la/la/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.contrib.auth import views as auth_views

from django.urls import path, include

from core.views import index, about
from client.views import ClientList
from userprofile.forms import LoginForm

urlpatterns = [
    path("", index, name="index"),
    path("dashboard/leads/", include('lead.urls')),
    path("dashboard/clients/", include('client.urls')),
    path("dashboard/teams/", include('team.urls')),
    path('dashboard/userprofile/', include('userprofile.urls')),
    path("dashboard/", include('dashboard.urls')),
    path("about/", about, name="about"),
    path("log-in/", views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path("log-out/", views.LogoutView.as_view(next_page='index'), name='logout'),

    path("admin/", admin.site.urls),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

la/lead/urls.py
from django.urls import path

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name= 'list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConverToClientView.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add/', views.LeadCreateView.as_view(), name='add'),
    path('export/', views.leads_export, name='export'),

]

la/lead/models.py
from django.contrib.auth.models import User
from django.db import models
from team.models import Team

class Lead(models.Model):
    LOW= 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    CHOICES_PRIORITY = (
        (LOW, 'Bajo'),
        (MEDIUM, 'Medio'),
        (HIGH, 'Alto'),
    )

    NEW = 'Nuevo'
    CONTEACTED = 'Contactado'
    WON = 'Ganador'
    LOST = 'Perdedor'

    CHOICES_STATUS = (
        (NEW, 'Nuevo'),
        (CONTEACTED, 'Contactado'),
        (WON, 'Ganador'),
        (LOST, 'Perdedor'),

    )

    team = models.ForeignKey(Team, related_name='leads', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    description = models.TextField(max_length=300, blank=True, null=True)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='lead', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

class LeadFile(models.Model):
    team = models.ForeignKey(Team, related_name='lead_files', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='leadfiles/')
    created_by = models.ForeignKey(User, related_name='lead_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True) 

    def __str__(self):

        return self.created_by.username

class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='lead_comments', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='lead_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):

        return self.created_by.username

la/lead/forms.py
from django import forms
from .models import Lead, Comment, LeadFile

WIDGET_ATTRS = {"class": "w-full py-4 px-6 rounded-xl bg-gray-100 mb-2"}

class AddLeadForm(forms.ModelForm):
    name = forms.CharField(
        label="Nombre",
        widget=forms.TextInput(attrs=WIDGET_ATTRS),
    )
    email = forms.EmailField(
        label="Correo Electrónico",
        widget=forms.TextInput(attrs=WIDGET_ATTRS),
    )
    description = forms.CharField(
        label="Descripción",
        widget=forms.Textarea(attrs={"rows": "5", "class": "mb-2 w-full bg-gray-100 rounded-xl"}),
    )
    priority = forms.ChoiceField(
        label="Prioridad",
        choices=Lead.CHOICES_PRIORITY,
        widget=forms.Select(attrs=WIDGET_ATTRS),
    )
    status = forms.ChoiceField(
        label="Estado",
        choices=Lead.CHOICES_STATUS,
        widget=forms.Select(attrs=WIDGET_ATTRS),
    )

    class Meta:
        model = Lead
        fields = ("name", "email", "description", "priority", "status")

class AddCommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={"rows": "5", "class": "w-full bg-gray-100 rounded-xl"}))

    class Meta:
        model = Comment
        fields = ['content']

class AddFileForm(forms.ModelForm):
    class Meta:
        model = LeadFile
        fields = ('file',)

la/lead/views.py
import csv
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (ListView, DetailView, DeleteView, UpdateView, CreateView, View,)

from .forms import AddCommentForm, AddFileForm, AddLeadForm
from .models import Lead

from client.models import Client, Comment as ClientComment
from team.models import Team

def leads_export(request):
    leads = Lead.objects.filter(created_by=request.user)

    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="clients.csv"'},
    )

    # Cambiar el delimitador a punto y coma
    writer = csv.writer(response, delimiter=';')

    # Escribir la fila de encabezado
    writer.writerow(['Lead', 'Description', 'Created at', 'Created by'])

    # Escribir datos de clientes
    for lead in leads:
        writer.writerow([lead.name, lead.description, lead.created_at, lead.created_by])

    return response

class LeadListView(LoginRequiredMixin, ListView):
    model = Lead

    def get_queryset(self):
        queryset = super(LeadListView, self).get_queryset()
        return queryset.filter(created_by=self.request.user, converted_to_client=False)

class LeadDetailView(LoginRequiredMixin, DetailView):
    model = Lead

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = AddCommentForm()
        context['fileform'] = AddFileForm

        return context

    def get_queryset(self):
        queryset = super(LeadDetailView, self).get_queryset()
        team = self.request.user.userprofile.active_team

        return queryset.filter(team=team, pk=self.kwargs.get('pk'))

class LeadDeleteView(LoginRequiredMixin, DeleteView):
    model = Lead
    success_url = reverse_lazy("leads:list")


    def get_queryset(self):
        queryset = super(LeadDeleteView, self).get_queryset()
        team = self.request.user.userprofile.active_team
        messages.success(self.request, 'El prospecto ha sido eliminado exitosamente.')  # Mensaje que se mostrará

        return queryset.filter(team=team, pk=self.kwargs.get('pk'))

    def get(self, request, *args, **kwargs):
        
        return self.post(request, *args, **kwargs)

class LeadUpdateView(LoginRequiredMixin, UpdateView):
    model = Lead
    form_class = AddLeadForm
    success_url = reverse_lazy("leads:list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Edit lead"
        return context

    def form_valid(self, form):
        messages.success(self.request, 'El prospecto ha sido actualizado exitosamente.')
        return super().form_valid(form)

    def get_queryset(self):
        queryset = super(LeadUpdateView, self).get_queryset()
        team = self.request.user.userprofile.active_team
        return queryset.filter(team=team, pk=self.kwargs.get('pk'))
        
class LeadCreateView(LoginRequiredMixin, CreateView):
    model = Lead
    form_class = AddLeadForm  # Utiliza tu formulario personalizado aquí
    success_url = reverse_lazy("leads:list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        team = self.request.user.userprofile.get_active_team()
        context["team"] = team
        context["title"] = "Agregar Cliente Potencial"
        return context

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.team = self.request.user.userprofile.get_active_team()
        messages.success(self.request, "Cliente potencial creado exitosamente!")
        return super().form_valid(form)
        

class AddFileView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')

        form = AddFileForm(request.POST, request.FILES)

        if form.is_valid():
            file = form.save(commit=False)
            file.team = self.request.user.userprofile.get_active_team()
            file.lead_id = pk
            file.created_by = request.user
            file.save()

        return redirect('leads:detail', pk=pk)
 
class AddCommentView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')

        form = AddCommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.team = self.request.user.userprofile.get_active_team()
            comment.created_by = request.user
            comment.lead_id = pk
            comment.save()

        return redirect('leads:detail', pk=pk)

class ConverToClientView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get("pk")

        team = self.request.user.userprofile.active_team

        lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
        team = self.request.user.userprofile.get_active_team()
        
        client = Client.objects.create(
            name=lead.name,
            email=lead.email,
            description=lead.description,
            created_by=request.user,
            team=team,
        )
        lead.converted_to_client = True
        lead.save()

        #convertir comentarios de clientes potenciales para convertir comentarios de clientes

        comments = lead.comments.all()

        for comment in comments:
            ClientComment.objects.create(
                client=client,
                content=comment.content,
                created_by=comment.created_by,
                team=team
            )

        messages.success(request, "El cliente potencial ha sido convertido en cliente.")

        return redirect("leads:list")

la/lead/templates/lead/lead_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ lead.name }}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">{{ lead.name }}</h1>

        {% if lead.description %}
            <p class="font-semibold">Nombre</p>
            <p class="mb-2">{{ lead.description }}</p>
        {% endif %}

        <p class="font-semibold">Prioridad</p>
        <p class="mb-2">{{ lead.get_priority_display }}</p>

        <p class="font-semibold">Estado</p>
        <p class="mb-2">{{ lead.get_status_display }}</p>

        <p class="font-semibold">Creado en</p>
        <p class="mb-2">{{ lead.created_at }}</p>

        <p class="font-semibold">Modificado en</p>
        <p class="mb-6">{{ lead.modified_at }}</p>

        <hr class="my-4">

        <form id="lead_delete_form" method="post" action="{% url 'leads:delete' lead.id %}">
            {% csrf_token %}
        </form>

        <a href="{% url 'leads:convert' lead.id %}" class="py-2 px-4 rounded-xl bg-blue-500 text-white">Convertir a cliente</a>
        <a href="{% url 'leads:edit' lead.id %}" class="py-2 px-4 rounded-xl bg-teal-500 text-white">Editar</a>
        <a href="#" onclick="document.getElementById('lead_delete_form').submit();" class="py-2 px-4 rounded-xl bg-red-500 text-white">Eliminar</a>

        <hr class="my-4">

        <h2 class="mb-6 text-xl">Comentarios</h2>

        <div class="space-y-4">
            {% for comment in lead.comments.all %}
                <div class="bg-gray-100 p-6 rounded-xl">
                    <p class="mb-2"><strong>{{ comment.created_by }}</strong> @ {{ comment.created_at }}</p>
                    
                    {{ comment.content }}
                </div>
            {% endfor %}
        </div>

        <form method="post" action="{% url 'leads:add_comment' lead.id %}">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="py-2 px-4 rounded-xl bg-blue-500 text-white">Enviar</button>
        </form>

        <hr class="my-4">

        <h2 class="mb-6 text-xl">Archivos</h2>

        <div class="space-y-4">
            {% for file in lead.files.all %}
                <div class="bg-gray-100 p-6 rounded-xl">
                    <p class="mb-2"><strong>{{ file.created_by }}</strong> @ {{ file.created_at }}</p>
                    
                    <a href="{{ file.file.url }}" class=" bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Descargas</a>
                </div>
            {% endfor %}
        </div>

        <form method="post" action="{% url 'leads:add_file' lead.id %}" enctype="multipart/form-data">
            {% csrf_token %}

            {{ fileform.as_p }}

            <button class="my-3 py-2 px-4 rounded-xl bg-blue-500 text-white">Subir</button>
        </form>

        <hr class="my-4">

        <a href="{% url 'leads:list' %}" class="pbg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Regreso</a>
    </div>
{% endblock %}

la/lead/templates/lead/lead_form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl">{{ title }}</h1>

        {% if team.get_plan.max_leads > team.leads.count or title == 'Edit lead' %}
            <form method="post" action=".">
                {% csrf_token %}

                {{ form.as_p }}

                <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Enviar</button>
            </form>
        {% else %}
            <div class="mt-6 px-6 py-4 bg-red-400 rounded-xl text-white">
                Tu equipo ha alcanzado el número máximo de clientes potenciales. ¡Tu propietario debe actualizar tu plan!</div>
        {% endif %}
    </div>
{% endblock %}

la/lead/templates/lead/lead_list.html
{% extends 'core/base.html' %}

{% block title %}Potenciales Clientes{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">Potenciales Clientes</h1>

        <a href="{% url 'leads:add' %}" class="inline-block py-4 px-6 bg-teal-600 rounded-xl text-white">Agregar cliente en potencia</a>
        <a href="{% url 'leads:export' %}" class="inline-block py-4 px-6 rounded-xl bg-teal-500 text-white">Exportar clientes potenciales</a>
    
        {% if object_list %}
            <div class="mt-6 flex justify-between">
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Nombre</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Prioridad</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Estado</p>
            </div>

            {% for lead in object_list %}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        <a href="{% url 'leads:detail' lead.id %}">{{ lead.name }}</a>
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ lead.get_priority_display }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ lead.get_status_display }}</p>
                </div>
            {% endfor %}
        {% else %}
            <p class="mt-6 px-2">Aún no hay clientes potenciales en la base de datos...</p>
        {% endif %}
    </div>
{% endblock %}