la/client/urls.py
from django.urls import path, include
from . import views
from .views import ClientList, Client_DetApi
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('clients', views.ClientViewSets)
app_name = 'clients'

urlpatterns = [
    path("", views.clients_list, name="list"),
    path("<int:pk>/", views.clients_detail, name="detail"),
    path("<int:pk>/delete/", views.clients_delete, name="delete"),
    path("<int:pk>/edit/", views.clients_edit, name="edit"),
    path("<int:pk>/add-comment/", views.clients_detail, name="add_comment"),
    path("<int:pk>/add-file/", views.clients_add_file, name='add_file'),
    path("add/", views.clients_add, name="add"),
    path('export/', views.clients_export, name='export'),
    
    path('api/', ClientList.as_view(), name='api'),  
    path('detapi/<int:pk>', Client_DetApi.as_view(), name='detapi'),
    path('router/', include(router.urls), name='router'),
]

la/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
     path('', views.dashboard, name='index'),
]

la/la/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.contrib.auth import views as auth_views

from django.urls import path, include

from core.views import index, about
from client.views import ClientList
from userprofile.forms import LoginForm

urlpatterns = [
    path("", index, name="index"),
    path("dashboard/leads/", include('lead.urls')),
    path("dashboard/clients/", include('client.urls')),
    path("dashboard/teams/", include('team.urls')),
    path('dashboard/userprofile/', include('userprofile.urls')),
    path("dashboard/", include('dashboard.urls')),
    path("about/", about, name="about"),
    path("log-in/", views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path("log-out/", views.LogoutView.as_view(next_page='index'), name='logout'),

    path("admin/", admin.site.urls),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

la/lead/urls.py
from django.urls import path

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name= 'list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConverToClientView.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add/', views.LeadCreateView.as_view(), name='add'),
    path('export/', views.leads_export, name='export'),

]

la/team/urls.py
from django.urls import path

from . import views

app_name = 'team'

urlpatterns = [
    path('', views.teams_list, name='list'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit_team, name='edit'),
    path('<int:pk>/activate/', views.teams_activate, name='activate'),

]

la/core/models.py
from django.db import models

# Create your models here.

la/core/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'core/index.html')

def about(request):
    return render(request, 'core/about.html')

la/core/templates/core/partials/footer.html
<footer class="mt-auto py-8 text-center bg-gray-200">
  <p class="text-xs text-gray-700">Copyright (c) 2023 CRM</p>
</footer>

la/core/templates/core/partials/nav.html
<nav class="py-6 px-6 flex justify-between bg-teal-500">
    <div class="h-13">
        <div class="h-20 min-h-full">
            <a href="/" class="text-white text-lg font-bold">
                <img src="https://seeklogo.com/images/I/inacap-logo-A8FDDFEFB2-seeklogo.com.png" alt="Logo" class="w-20 h-10" />
            </a>
        </div>
    </div>
    <div class="space-x-4">
        <button class="py-4 px-6 bg-teal-800 hover:bg-blue-700 rounded-xl text-white font-bold">
        <a href="{% url 'about' %}">Nosotros</a>
        </button>
        {% if request.user.is_authenticated %} {% if active_team and active_team.id %}
        <a href="{% url 'team:detail' active_team.id %}" class="py-4 px-6 bg-teal-600 hover:bg-blue-700 rounded-xl text-white font-bold">{{ active_team.name }}</a>
        {% endif %}
        <a href="{% url 'dashboard:index' %}" class="py-4 px-6 bg-teal-600 rounded-xl hover:bg-blue-700 text-white font-bold">Panel de control</a>
        <a href="{% url 'leads:list' %}" class="py-4 px-6 bg-teal-600 rounded-xl hover:bg-blue-700 text-white font-bold">Clientes potenciales</a>
        <a href="{% url 'clients:list' %}" class="py-4 px-6 bg-teal-600 rounded-xl hover:bg-blue-700 text-white font-bold">Clientes</a>
        <a href="{% url 'userprofile:myaccount' %}" class="py-4 px-6 bg-teal-800 hover:bg-blue-700 rounded-xl text-white font-bold">Mi Cuenta</a>
        {% else %}
        <a href="{% url 'login' %}" class="py-4 px-6 bg-teal-600 rounded-xl hover:bg-blue-700 text-white font-bold">Iniciar sesión</a>
        <a href="{% url 'userprofile:signup' %}" class="py-4 px-6 bg-teal-300 rounded-xl hover:bg-blue-700 text-white font-bold">Registrarse</a>
        {% endif %}
    </div>
</nav>