la/client/urls.py
from django.urls import path, include
from . import views
from .views import ClientList, Client_DetApi
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('clients', views.ClientViewSets)
app_name = 'clients'

urlpatterns = [
    path("", views.clients_list, name="list"),
    path("<int:pk>/", views.clients_detail, name="detail"),
    path("<int:pk>/delete/", views.clients_delete, name="delete"),
    path("<int:pk>/edit/", views.clients_edit, name="edit"),
    path("<int:pk>/add-comment/", views.clients_detail, name="add_comment"),
    path("<int:pk>/add-file/", views.clients_add_file, name='add_file'),
    path("add/", views.clients_add, name="add"),
    path('export/', views.clients_export, name='export'),
    
    path('api/', ClientList.as_view(), name='api'),  
    path('detapi/<int:pk>', Client_DetApi.as_view(), name='detapi'),
    path('router/', include(router.urls), name='router'),
]

la/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
     path('', views.dashboard, name='index'),
]

la/la/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.contrib.auth import views as auth_views

from django.urls import path, include

from core.views import index, about
from client.views import ClientList
from userprofile.forms import LoginForm

urlpatterns = [
    path("", index, name="index"),
    path("dashboard/leads/", include('lead.urls')),
    path("dashboard/clients/", include('client.urls')),
    path("dashboard/teams/", include('team.urls')),
    path('dashboard/userprofile/', include('userprofile.urls')),
    path("dashboard/", include('dashboard.urls')),
    path("about/", about, name="about"),
    path("log-in/", views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path("log-out/", views.LogoutView.as_view(next_page='index'), name='logout'),

    path("admin/", admin.site.urls),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

la/lead/urls.py
from django.urls import path

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name= 'list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConverToClientView.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add/', views.LeadCreateView.as_view(), name='add'),
    path('export/', views.leads_export, name='export'),

]

la/dashboard/models.py
from django.db import models

# Create your models here.

la/lead/models.py
from django.contrib.auth.models import User
from django.db import models
from team.models import Team

class Lead(models.Model):
    LOW= 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    CHOICES_PRIORITY = (
        (LOW, 'Bajo'),
        (MEDIUM, 'Medio'),
        (HIGH, 'Alto'),
    )

    NEW = 'Nuevo'
    CONTEACTED = 'Contactado'
    WON = 'Ganador'
    LOST = 'Perdedor'

    CHOICES_STATUS = (
        (NEW, 'Nuevo'),
        (CONTEACTED, 'Contactado'),
        (WON, 'Ganador'),
        (LOST, 'Perdedor'),

    )

    team = models.ForeignKey(Team, related_name='leads', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    description = models.TextField(max_length=300, blank=True, null=True)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='lead', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

class LeadFile(models.Model):
    team = models.ForeignKey(Team, related_name='lead_files', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='leadfiles/')
    created_by = models.ForeignKey(User, related_name='lead_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True) 

    def __str__(self):

        return self.created_by.username

class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='lead_comments', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='lead_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):

        return self.created_by.username

la/dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from lead.models import Lead
from client.models import Client
from team.models import Team

@login_required
def dashboard(request):
    team = request.user.userprofile.get_active_team()

    leads = Lead.objects.filter(team=team, converted_to_client=False).order_by('-created_at')[0:5]
    clients = Client.objects.filter(team=team).order_by('-created_at')[0:5]

    return render(request, 'dashboard/dashboard.html', {
        'leads': leads,
        'clients': clients,
    })

la/dashboard/templates/dashboard/dashboard.html
{% extends "core/base.html" %}

{% block title %}Panel de control{% endblock %}

{% block content %}
<div class="py-6 px-6">
    <h1 class="mb-6 text-xl font-bold">Panel de control</h1>

    <div class="flex space-x-4">
        <div class="w-1/2 px-4 py-6 bg-gray-100 rounded-xl leads">
            <h2 class="mb-4 text-lg font-bold">Los clientes potenciales más recientes</h2>

            {% for lead in leads %}
                <div class="mb-2 lead">
                    <h3 class="font-semibold">{{ lead.name }}</h3>

                    <p class="text-xs">Estado: {{ lead.get_status_display }}</p>
                    <p class="text-xs">Prioridad: {{ lead.get_priority_display }}</p>

                    <button class="mb-3 py-1 px-2 bg-teal-500 hover:bg-blue-700 text-white text-xs rounded-xl"><a href="{% url 'leads:detail' lead.pk %}">Detalles</a></button>
                </div>
            {% endfor %}

        </div>

        <div class="w-1/2 px-4 py-6 bg-gray-100 rounded-xl clients">   
            <h2 class="mb-4 text-lg font-bold">Cientes mas recientes</h2>

            {% for client in clients %}
                <div class="mb-2 client">
                    <h3 class="font-semibold">{{ client.name }}</h3>

                    <button class="mb-3 py-1 px-2 bg-teal-500 hover:bg-blue-700 text-white text-xs rounded-xl"><a href="{% url 'clients:detail' client.pk %}">Detalles</a></button>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}