la/client/urls.py
from django.urls import path, include
from . import views
from .views import ClientList, Client_DetApi
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('clients', views.ClientViewSets)
app_name = 'clients'

urlpatterns = [
    path("", views.clients_list, name="list"),
    path("<int:pk>/", views.clients_detail, name="detail"),
    path("<int:pk>/delete/", views.clients_delete, name="delete"),
    path("<int:pk>/edit/", views.clients_edit, name="edit"),
    path("<int:pk>/add-comment/", views.clients_detail, name="add_comment"),
    path("<int:pk>/add-file/", views.clients_add_file, name='add_file'),
    path("add/", views.clients_add, name="add"),
    path('export/', views.clients_export, name='export'),
    
    path('api/', ClientList.as_view(), name='api'),  
    path('detapi/<int:pk>', Client_DetApi.as_view(), name='detapi'),
    path('router/', include(router.urls), name='router'),
]

la/la/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.contrib.auth import views as auth_views

from django.urls import path, include

from core.views import index, about
from client.views import ClientList
from userprofile.forms import LoginForm

urlpatterns = [
    path("", index, name="index"),
    path("dashboard/leads/", include('lead.urls')),
    path("dashboard/clients/", include('client.urls')),
    path("dashboard/teams/", include('team.urls')),
    path('dashboard/userprofile/', include('userprofile.urls')),
    path("dashboard/", include('dashboard.urls')),
    path("about/", about, name="about"),
    path("log-in/", views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path("log-out/", views.LogoutView.as_view(next_page='index'), name='logout'),

    path("admin/", admin.site.urls),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

la/client/models.py
from django.contrib.auth.models import User
from django.db import models

from team.models import Team

class Client(models.Model):
    team = models.ForeignKey(Team, related_name='clients', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='clients', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
    
class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='client_comments', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='client_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):

        return self.created_by.username
    
class ClientFile(models.Model):
    team = models.ForeignKey(Team, related_name='client_files', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='clientfiles/')
    created_by = models.ForeignKey(User, related_name='client_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True) 

    def __str__(self):

        return self.created_by.username

la/client/forms.py
from django import forms

from .models import Client, Comment, ClientFile

class AddClientForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "mb-2 w-full py-4 px-6 rounded-xl bg-gray-100"})
    )
    email = forms.CharField(
        widget=forms.TextInput(attrs={"class": "mb-2 w-full py-4 px-6 rounded-xl bg-gray-100"})
    )
    description = forms.CharField(
        widget=forms.Textarea(attrs={"rows":"5", "class": "mb-2 w-full bg-gray-100 rounded-xl"})
    )

    class Meta:
        model = Client
        fields = ('name', 'email', 'description',)

class AddCommentForm(forms.ModelForm):
    content = forms.CharField(
        widget=forms.Textarea(attrs={"rows":"5", "class": "w-full bg-gray-100 rounded-xl"})
    )

    class Meta:
        model = Comment
        fields = ('content',)

class AddFileForm(forms.ModelForm):
    class Meta:
        model = ClientFile
        fields = ('file',)

la/client/views.py
import csv

from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from .forms import AddClientForm, AddCommentForm, AddFileForm
from .models import Client

from team.models import Team

from .serializers import ClientSerializer
from rest_framework.response import Response
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from rest_framework import generics, mixins
from django.http import Http404
from rest_framework import viewsets
from rest_framework.decorators import action




@login_required
def clients_export(request):
    clients = Client.objects.filter(created_by=request.user)

    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="clients.csv"'},
    )

    # Cambiar el delimitador a punto y coma
    writer = csv.writer(response, delimiter=';')

    # Escribir la fila de encabezado
    writer.writerow(['Client', 'Description', 'Created at', 'Created by'])

    # Escribir datos de clientes
    for client in clients:
        writer.writerow([client.name, client.description, client.created_at, client.created_by])

    return response

class ClientViewSets(LoginRequiredMixin, viewsets.ModelViewSet):
    queryset = Client.objects.all()
    serializer_class = ClientSerializer

class ClientList(LoginRequiredMixin, generics.ListCreateAPIView):
    queryset = Client.objects.all()
    serializer_class = ClientSerializer

    def get(self, request):
        if request.method == 'GET':
            team = request.user.userprofile.active_team
            clients = team.clients.all()
            serializer = ClientSerializer(clients, many=True)
            return Response(serializer.data)

    def post(self, request):
        if request.method == 'POST':
            serializer = ClientSerializer(data=request.data)
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data, status=status.HTTP_201_CREATED)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        
        # Redireccionar a otra página
        return redirect('otra_pagina')

@login_required
def clients_list(request):
    team = request.user.userprofile.active_team
    clients = team.clients.all()

    return render(request, "client/clients_list.html", {"clients": clients})    

@login_required
def clients_add_file(request, pk):
    if request.method == 'POST':
        form = AddFileForm(request.POST, request.FILES)

        if form.is_valid():
            file = form.save(commit=False)
            file.team = request.user.userprofile.active_team
            file.client_id = pk
            file.created_by = request.user
            file.save()
        
            return redirect('clients:detail', pk=pk)
    return redirect('clients:detail', pk=pk)    

class Client_DetApi(LoginRequiredMixin, generics.RetrieveUpdateDestroyAPIView):
    queryset = Client.objects.all()
    serializer_class = ClientSerializer
    
    def get_object(self):
        team = self.request.user.userprofile.active_team
        pk = self.kwargs.get('pk')
        return get_object_or_404(Client, created_by=self.request.user, pk=pk)

    def get(self, request, *args, **kwargs):
        client = self.get_object()
        serializer = ClientSerializer(client)
        return Response(serializer.data)

    def perform_update(self, serializer):
        serializer.save()

    def perform_destroy(self, instance):
        instance.delete()

    @action(detail=True, methods=['post'])
    def custom_action(self, request, *args, **kwargs):
        client = self.get_object()
        serializer = ClientSerializer(client, data=request.data)
        
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@login_required
def clients_detail(request, pk):
    team = request.user.userprofile.active_team
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form = AddCommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.team = request.user.userprofile.get_active_team()
            comment.created_by = request.user
            comment.client = client
            comment.save()

            return redirect('clients:detail', pk=pk)
    
    else:
        form = AddCommentForm()

    return render(request, "client/clients_detail.html", {
        "client": client, 
        "form": form, 
        "fileform" : AddFileForm(),
    })

@login_required
def clients_add(request):
    team = request.user.userprofile.get_active_team()

    if request.method == "POST":
        form = AddClientForm(request.POST)

        if form.is_valid():            
            client = form.save(commit=False)
            client.created_by = request.user
            client.team = team
            client.save()

            messages.success(request, "El cliente fue creado.")

            return redirect("clients:list")
    else:
        form = AddClientForm()

    return render(request, "client/clients_add.html", {"form": form, "team": team})


@login_required
def clients_delete(request, pk):
    team = request.user.userprofile.active_team
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    client.delete()

    messages.success(request, "El cliente fue eliminado")

    return redirect("clients:list")


@login_required
def clients_edit(request, pk):
    team = request.user.userprofile.active_team
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == "POST":
        form = AddClientForm(request.POST, instance=client)

        if form.is_valid():
            form.save()

            messages.success(request, "Los cambios fueron guardados.")

            return redirect("clients:list")
    else:
        form = AddClientForm(instance=client)

    return render(request, "client/clients_edit.html", {"form": form})

la/client/templates/client/clients_add.html
{% extends "core/base.html" %}

{% block title %}Agregar Cliente{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl mb-3">Agregar Cliente</h1>

        {% if team.plan.max_clients > team.clients.all|length %}
            <form method="post" action=".">
                {% csrf_token %}

                {{ form.as_p }}

                <button class="mb-3 py-4 px-8 bg-teal-500  hover:bg-blue-700 text-white rounded-xl">Enviar</button>

            </form>  
        {% else %} 
            <div class="mt-6 px-6 py-4 bg-red-400 rounded-xl text-white">
                Tu equipo ha alcanzado el número máximo de clientes. ¡Tu propietario debe actualizar tu plan!
            </div>
        {% endif %}
    </div>
{% endblock %}

la/client/templates/client/clients_detail.html
{% extends "core/base.html" %}

{% block title %}{{ client.name }}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">{{ client.name }}</h1>
    
        {% if client.description %}
            <p class="font-semibold">Descripción</p>
            <p class="mb-2">{{ client.description }}</p>
        {% endif %}

        <p class="font-semibold">Creado en</p>
        <p class="mb-2">{{ client.created_at }}</p>

        <p class="font-semibold">Modificado en</p>
        <p class="mb-6">{{ client.modified_at }}</p>

        <hr class="my-4">
        <a href="{% url 'clients:detapi' client.id %}" class="py-2 px-4 rounded-xl bg-teal-500 text-white">Editar Api</a>
        <a href="{% url 'clients:edit' client.id %}" class="py-2 px-4 rounded-xl bg-teal-500 text-white">Editar</a>
        <a href="{% url 'clients:delete' client.id %}" class="py-2 px-4 rounded-xl bg-red-500 text-white">Eliminar</a>
        
        <hr class="my-4">

        <h2 class="mb-6 text-xl">Comentarios</h2>

        <div class="space-x-4">
            {% for comment in client.comments.all %}
                <div class="bg-gray-100 p-6 rounded-xl">
                    <p class="mb-2"><strong>{{ comment.created_by }}</strong> @ {{ comment.created_at }}</p>
                    
                    {{ comment.content }}

                </div>
            {% endfor %}
        </div>

        <form method="post" action="{% url 'clients:add_comment' client.id %}">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="py-2 px-4 rounded-xl bg-blue-500 text-white">Enviar</button>

        </form>

    </form>

    <hr class="my-4">

    <h2 class="mb-6 text-xl">Files</h2>

    <div class="space-y-4">
        {% for file in client.files.all %}
        <div class="bg-gray-100 p-6 rounded-xl">
            <p class="mb-2"><strong>{{ file.created_by }}</strong> @ {{ file.created_at }}</p>
            
            <a href="{{ file.file.url }}" class=" bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Descargas</a>
        </div>
        {% endfor %}
    </div>

    <form method="post" action="{% url 'clients:add_file' pk=client.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ fileform.as_p }}
        <button class="my-3 py-2 px-4 rounded-xl bg-blue-500 hover:bg-blue-700 text-white">Subir</button>
    </form>

        <hr class="my-4">

        <a href="{% url 'clients:list' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Regresar</a>
    </div>
{% endblock %}

la/client/templates/client/clients_edit.html
{% extends "core/base.html" %}

{% block title %}Editar Cliente{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl">Editar cliente</h1>
        <form method="post" action=".">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="py-4 px-8 bg-teal-500  hover:bg-blue-700 text-white rounded-xl">Enviar</button>

        </form>   
    </div>
{% endblock %}

la/client/templates/client/clients_list.html
{% extends 'core/base.html' %}

{% block title %}
  Clientes
{% endblock %}

{% block content %}
  <div class="py-6 px-6">
    <h1 class="mb-4 text-xl">Clientes</h1>

    <a href="{% url 'clients:add' %}" class="inline-block py-4 px-6 bg-teal-600 rounded-xl hover:bg-blue-700 text-white">Agregar clientes</a>
    <a href="{% url 'clients:export' %}" class="inline-block py-4 px-6 rounded-xl bg-teal-500 hover:bg-blue-700 text-white">Exportar clientes</a>
    <a href="{% url 'clients:api' %}" class="inline-block py-4 px-6 rounded-xl bg-teal-500 hover:bg-blue-700 text-white">Clientes Api</a>
    
    {% if clients %}
      <div class="mt-5 flex justify-between">
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Nombre</p>
      </div>
      {% for client in clients %}
        <div class="flex justify-between">
          <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
            <a href="{% url 'clients:detail' client.id %}">{{ client.name }}</a>
          </p>
        </div>
      {% endfor %}
    {% else %}
      <p class="mt-6 px-2">No hay clientes en la base de datos todavía...</p>
    {% endif %}
  </div>
{% endblock %}